
title: Appulse
description: >-
  Appulse aims to build correct concurrent and
  scalable applications based on JVM and BEAM.

baseurl:  ""
url:      https://appulse.io
email:    appulse.io@gmail.com

twitter_username: appulseprojects
github_username:  appulse-projects
header_pages:
  - 00_get-started.md
  - 01_advanced-usage.md
  - 02_benchmarks.md

markdown: kramdown

# https://github.com/jekyll/minima
theme: minima

sass:
  style: compressed

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
