
title: Appulse
description: >-
  Appulse aims to build correct concurrent and
  scalable applications based on JVM and BEAM.

baseurl:  ""
url:      https://appulse.io
email:    appulse.io@gmail.com

twitter_username: appulseprojects
github_username:  appulse-projects
gitter_room: appulse-projects/encon

header_pages:
  - pinned/get-started.md
  - pinned/advanced-usage.md
  - pinned/examples.md

markdown: kramdown

# https://github.com/jekyll/minima
theme: minima

sass:
  style: compressed

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
